//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoangNV.HotelBooking.BusinessLogic.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserUpdateViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserUpdateViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoangNV.HotelBooking.BusinessLogic.Resources.Models.UserUpdateViewModel", typeof(UserUpdateViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Display_Email {
            get {
                return ResourceManager.GetString("Display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string Display_FullName {
            get {
                return ResourceManager.GetString("Display_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Display_Password {
            get {
                return ResourceManager.GetString("Display_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại.
        /// </summary>
        internal static string Display_PasswordSecond {
            get {
                return ResourceManager.GetString("Display_PasswordSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền người dùng.
        /// </summary>
        internal static string Display_Role {
            get {
                return ResourceManager.GetString("Display_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string Display_UserName {
            get {
                return ResourceManager.GetString("Display_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} đã tồn tại..
        /// </summary>
        internal static string E_A_004_01 {
            get {
                return ResourceManager.GetString("E_A_004_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} không đúng với mật khẩu.
        /// </summary>
        internal static string E_A0001_02 {
            get {
                return ResourceManager.GetString("E_A0001_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} không được bỏ trống..
        /// </summary>
        internal static string E_A002_02 {
            get {
                return ResourceManager.GetString("E_A002_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} không được nhỏ hơn {MinLength} ký tự..
        /// </summary>
        internal static string E_C_0001_01 {
            get {
                return ResourceManager.GetString("E_C_0001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} không đúng định dạng..
        /// </summary>
        internal static string E_C_001_09 {
            get {
                return ResourceManager.GetString("E_C_001_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} không được vượt quá {MaxLength} ký tự..
        /// </summary>
        internal static string E_C_008_02 {
            get {
                return ResourceManager.GetString("E_C_008_02", resourceCulture);
            }
        }
    }
}
